#!/usr/bin/env bash
# Setup 404 page
sudo echo -e "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
