#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code, and displays this data.

script_dir=$(pwd)
file_name="apache-access.log"
file_path="$script_dir/$file_name"

awk '{ count[$1" "$9]++ } END {	for (key in count) { printf "\t%d %s\n", count[key], key } } ' "$file_path" | sort -nr
