#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code, and displays this data.

script_dir=$(pwd)
file_name="apache-access.log"
file_path="$script_dir/$file_name"

awk '{ print $1, $9 } ' "$file_path" | sort | uniq -c | sort -nr
