#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

LIMIT=10	# 10 iterations.
a=1

while [ "$a" -le $LIMIT ]
do
	echo "Best School"
	if [ "$a" == 9 ]
	then
		echo "Hi"
	fi
	(( a+= 1 ))
done

exit 0
